[package]
name = "midir_browser_example"
version = "0.0.0"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
midir = { "path" = "../.." }

console_error_panic_hook = "0.1.6"
web-sys = { version = "0.3", features = ["console"]}
js-sys = "0.3"
wasm-bindgen = "0.2"
